# Generated by Django 5.1.3 on 2026-03-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_stylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('stylist', 'Stylist'), ('guest', 'Guest')], default='member', max_length=10),
        ),
    ]
