# Generated by Django 5.1.3 on 2026-03-17 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_booking_stylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stylist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_as_stylist', to=settings.AUTH_USER_MODEL),
        ),
    ]
