# Generated by Django 5.1.3 on 2026-03-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_alter_booking_stylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stylist',
        ),
    ]
